# 2)Create a program that will play the “cows and bulls” game with the user. The game works like this:

# Randomly generate a 4-digit number. Ask the user to guess a 4-digit number. 
# For every digit that the user guessed correctly in the correct place, they have a “cow”. 
# For every digit the user guessed correctly in the wrong place is a “bull.” 
# Every time the user makes a guess, tell them how many “cows” and “bulls” they have. 
# Once the user guesses the correct number, the game is over. 
# Keep track of the number of guesses the user makes throughout teh game and tell the user at the end.

# Say the number generated by the computer is 1038. An example interaction could look like this:

#   Welcome to the Cows and Bulls Game! 
#   Enter a number: 
#   >>> 1234
#   2 cows, 0 bulls
#   >>> 1256
#   1 cow, 1 bull

print("Welcome to the game called Cows and Buuls")
import random
rand_num = random.randrange(1000, 10000) # randomly generated 4 digit number
# print(rand_num) # just to check the number randomly generated byt computer
guess_num = 1 # number of tries user made to guess the random number
user_number = int(input("Please enter a 4-digit number to play the game:\n"))
while True:
  comp_num_list = list(str(rand_num))
  user_num_list = list(str(user_number))
  cows = 0
  bulls = 0
  if user_number == rand_num:
    if guess_num == 1:
      print("Congrats, you have guessed the correct number from first try!")
    elif guess_num > 1:
      print ("Congrats, you have guessed the correct number from", guess_num, "tries!")
    break
  else:
    for key_u, value_u in enumerate(user_num_list): # key/value pair for any element in the number enetered by user
      for key_c, value_c in enumerate(comp_num_list): # key/value pair for any element in the randomly generated number
        if value_u == value_c and key_u == key_c:
          cows += 1
        elif value_u == value_c and key_u != key_c:
          bulls += 1
    guess_num += 1
    print("You have", cows, "cows and", bulls, "bulls!")
  user_number = int(input("Your guess was wrong, please etry again:\n"))